---
abstract: 'determine if a mime type is compressible'
author:
  - 'Mike Greb <michael@thegrebs.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.3, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Compressible
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
version: 0.01
x_contributors:
  - 'mikegrb <mgreb@linode.com>'
